name=machine-hawk-inferencing
version=1.0.2
author=EdgeImpulse Inc.
maintainer=EdgeImpulse Inc.
sentence=Arduino library for running machine learning models
paragraph=This library contains the signal processing code and machine learning models to classify real-world data for Machine Hawk predictive maintenance.
category=Data processing
url=https://forum.edgeimpulse.com/
depends=
includes=machine-hawk-inferencing.h