; PlatformIO Project Configuration File
; Docs: https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial settings
monitor_speed = 115200

; Include local model libraries
lib_extra_dirs = ../model

; Libraries (add as needed)
lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9


; Build flags (for Edge Impulse model)
build_flags =
    -DEI_SENSOR_AUX
    -DEI_SENSOR_FFT
    -DEI_SENSOR_ML


