; PlatformIO Project Configuration File
; Docs: https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial settings
monitor_speed = 115200

; Libraries (add as needed)
lib_deps =
    edgeimpulse/edge-impulse-sdk
    bblanchon/ArduinoJson @ ^6.21.2
    knolleary/PubSubClient @ ^2.8
    thingsboard/ThingsBoard @ ^0.9.0


; Build flags (for Edge Impulse model)
build_flags =
    -DEI_SENSOR_AUX
    -DEI_SENSOR_FFT
    -DEI_SENSOR_ML


